name: pull-request
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  hello_world_job:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello World
        run: echo "Hello World 2"
